/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Board = IDL.Variant({ 'CBSE' : IDL.Null, 'ICSE' : IDL.Null });
export const Registration = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'board' : Board,
  'phone' : IDL.Text,
  'className' : IDL.Text,
  'parentName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'register' : IDL.Func([Registration], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Board = IDL.Variant({ 'CBSE' : IDL.Null, 'ICSE' : IDL.Null });
  const Registration = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'board' : Board,
    'phone' : IDL.Text,
    'className' : IDL.Text,
    'parentName' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getRegistrationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'register' : IDL.Func([Registration], [], []),
  });
};

export const init = ({ IDL }) => { return []; };